name: Verify PR
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode verify
      - run: mkdir dist && cp cli/target/*.tar.gz dist
      - uses: actions/upload-artifact@v2
        with:
          name: cli.tar.gz
          path: dist
          retention-days: 7